script:
- |
  git config user.name "unifi-poller"
  git config user.email "code@golift.io"
  git remote remove origin
  git remote add origin https://$GITHUB_API_KEY@github.com/unifi-poller/wiki.git > /dev/null 2>&1
  git remote add upstream https://$GITHUB_API_KEY@github.com/unifi-poller/unifi-poller.wiki.git > /dev/null 2>&1
  git fetch origin
  git fetch upstream
  git merge upstream/master --no-edit
  git push origin HEAD:master > /dev/null 2>&1
  git push upstream HEAD:master > /dev/null 2>&1
env:
  matrix:
    secure: "YjNrEJBcSPa0PcMuUH4Kzl4Nsf7DiIyh9Hz5G4BsSJ8nPnIfZHgvt6uIwcR8Fl0qaT09242BprUQ6HOsXR2VVq0kP+2Oycf2Y71LnvLY0/ZuGWnkYH7kqJ4hHWlQcy4DMZsV8U50TagBII4NqzQwdd5RXDEcFoiVbKSzFnm+yQ2lkq+TQSwTS7AWfF17XCltIc9YwE6XVsWuIThdMUXyOy2Pj6DzauyNGf9KRmWeKeyWqTmtlid3S2Hg0kSoRIqGUvtOnX3pn1JMF+EYGxrDB8rQW99zBRGj7fmx2k41226IAYsVUG4rn+J70WiEclNcMu2lxwePLCqaE018PRNmbSwSKgvSjV5A8Z+TtmW27vqF6AoE5WYm7zVRzPQwxRScoHQj1B+J/KeI5K27eFySxjDE4bAIS4mUX0+jjjSgOv8BxNggd8bhKID9c5WF5H3FjoLVuSQ1pHqKpLrJPG0GCW6PRzZLOw8NRGXz5sRcVorIRXz/5f+UYgTqJ5HcV11IzlPHgO4voyJV19MI+urqTEdtAByrIvwbozn+jcDWlZ8evdiVE2GakDGCmcXowMT4aXJ9It1rwKl8+8qqMZMsrX7FYYnB0jsHSuUzpNXM/F+bS3ziLXUONjv0fwKqRrKdAyxuF2awZxV3AEMXOag8BF9cNsw0uYTtm1RNuePCWQY="
